### ISSUE TITLE
Docker build in examples failing with error

### ISSUE THREAD

**Issue by krishnaarava** [lyft/flinkk8soperator#115]
When I try to build an docker image in examples folder throws me an error. 

`docker build -t "onemoretest:1.0" . `

> Step 19/25 : RUN set -ex;   wget -nv -O flink.tgz "$FLINK_TGZ_URL";     tar -xf flink.tgz --strip-components=1;   rm flink.tgz;     cp ./opt/flink-s3-fs-presto-1.8.1.jar ./lib/;  cp ./opt/flink-s3-fs-hadoop-1.8.1.jar ./lib/;    chown -R flink:flink .;
>  ---> Running in b908558f3836
> + wget -nv -O flink.tgz https://mirrors.ocf.berkeley.edu/apache/flink/flink-1.8.1/flink-1.8.1-bin-scala_2.12.tgz
> https://mirrors.ocf.berkeley.edu/apache/flink/flink-1.8.1/flink-1.8.1-bin-scala_2.12.tgz:
> 2019-10-04 22:11:18 ERROR 404: Not Found.

Looks like the path if no more available https://mirrors.ocf.berkeley.edu/apache/flink/flink-1.8.1/

**Comment by anandswaminathan** [comment]
Looks like 1.8.1 is no longer available. Only 1.8.2 is present. Let me submit a PR

**Comment by anandswaminathan** [comment]
https://github.com/lyft/flinkk8soperator/pull/116
