### ISSUE TITLE
kubectl apply -f on running cluster

### ISSUE THREAD

**Issue by aleksandr-spb** [lyft/flinkk8soperator#132]
Hello!
I have next FlinkApplication:
[flink-operator-demo-yaml.txt](https://github.com/lyft/flinkk8soperator/files/3880361/flink-operator-demo-yaml.txt)
When I tried to update the configuration and run the command "kubectl apply -f flink-operator-demo-yaml.txt", I assumed that my flink cluster would restart with creating a savepoint and restore from the savepoint, but this did not happen.
Log of flinkk8operator:
[log.txt](https://github.com/lyft/flinkk8soperator/files/3880385/log.txt)

When i run "kubectl delete -f flink-operator-demo-yaml.txt" and then "kubectl create -f flink-operator-demo-yaml.txt" with "savepointPath", the flink cluster started with restoring from savepoint. 

Is it correct to try to update flink-cluster "on the fly" using "kubectl apply -f" or is this not supported ?

**Comment by anandswaminathan** [comment]
@aleksandr-spb 

If you check the logs - you can actually see that the Operator tried to update the cluster but the problem was the new cluster did not come up soon.

```ts="2019-11-22T18:49:30+03:00" level=info msg="Handling state for application" app_name=call-rating ns=flink-operator phase=ClusterStarting src="flink_state_machine.go:167"
ts="2019-11-22T18:49:40+03:00" level=info msg="Handling state for application" app_name=call-rating ns=flink-operator phase=ClusterStarting src="flink_state_machine.go:167"
ts="2019-11-22T18:49:40+03:00" level=info msg="Logged Warning event: ClusterCreationFailed: Flink cluster failed to become available: failed to make progress after 1m0s" app_name=call-rating ns=flink-operator phase=ClusterStarting src="flink.go:466"
ts="2019-11-22T18:49:40+03:00" level=info msg="Logged Warning event: RolledBackDeploy: Successfully rolled back deploy cf3e0fa7" app_name=call-rating ns=flink-operator phase=ClusterStarting src="flink.go:466"```

Would recommend setting higher value for like say `maxErrDuration: 15m` - for the operator config https://raw.githubusercontent.com/lyft/flinkk8soperator/v0.3.0/deploy/config.yaml

**Comment by aleksandr-spb** [comment]
It works fine.
In addition, I noticed that cluster did not start due to "insuffience CPU" reason. I fixed it and everything works fine.
Thanks.
