### ISSUE TITLE
Replace environment variable for configuration injection

### ISSUE THREAD

**Issue by tweise** [lyft/flinkk8soperator#135]
Environment variable `OPERATOR_FLINK_CONFIG` should be replaced with `FLINK_PROPERTIES` to support the stock Flink Docker images.

https://github.com/docker-flink/docker-flink/pull/82

We should also update the example to use that image.

**Comment by tweise** [comment]
Environment variable substitution merged upstream: https://github.com/docker-flink/docker-flink/pull/91

**Comment by mwylde** [comment]
Is there a way we can make this backwards compatible? Otherwise this will break people's existing images.

**Comment by tweise** [comment]
Yes, unfortunately it would break images if they were copied from the previous example. On the other hand, the operator will become compatible with the docker-flink images and custom cruft can just be deleted. Should we publish both environment variables for a while or just switch before going out of beta?

**Comment by mwylde** [comment]
Yeah, I think we would need to do something along those lines. Otherwise this is a breaking change that will be hard to manage for users.
