### ISSUE TITLE
Refers to #64

### ISSUE THREAD

**Issue by caryyu** [lyft/flinkk8soperator#139]
https://github.com/lyft/flinkk8soperator/issues/64

**Comment by anandswaminathan** [comment]
I don't think your #64 is related to the $HOST_IP issue. Can you paste the logs ?

Also if you believe it is the `$HOST_IP`, can you specify more details about the image you are using. Is it the example word count image ?

**Comment by caryyu** [comment]
@anandswaminathan  
well, I was using docker image of `docker.io/lyft/wordcount-operator-example:latest`, I doubt the issue was happening on below - `container.Env` which should sort by the first letter of env-vars and then `HOST_IP` then can be handled right, which I'm right or not, I don't know: 

`./flinkk8soperator/pkg/controller/flink/container_utils.go`
```
func InjectOperatorCustomizedConfig(deployment *appsv1.Deployment, app *v1beta1.FlinkApplication, hash string, deploymentType string) {
	var newContainers []v1.Container
	for _, container := range deployment.Spec.Template.Spec.Containers {
		var newEnv []v1.EnvVar
		for _, env := range container.Env {
			if env.Name == OperatorFlinkConfig {
				if isHAEnabled(app.Spec.FlinkConfig) {
					env.Value = fmt.Sprintf("%s\nhigh-availability.cluster-id: %s-%s\n", env.Value, app.Name, hash)
					if deploymentType == FlinkDeploymentTypeJobmanager {
						env.Value = fmt.Sprintf("%sjobmanager.rpc.address: $HOST_IP\n", env.Value)
					}
				} else {
					env.Value = fmt.Sprintf("%s\njobmanager.rpc.address: %s\n", env.Value, VersionedJobManagerServiceName(app, hash))
				}
				if deploymentType == FlinkDeploymentTypeTaskmanager {
					env.Value = fmt.Sprintf("%staskmanager.host: $HOST_IP\n", env.Value)
				}
			}
			newEnv = append(newEnv, env)
		}
		container.Env = newEnv
		newContainers = append(newContainers, container)
	}
	deployment.Spec.Template.Spec.Containers = newContainers
}

```

The log or error was the same from PR #64, which I think the symbol of `$HOST_IP` was being put as a hostname, which the program couldn't recognize right and throw an error, by the way, is it normal on your local docker kubernetes environment for this? 

My installation(v0.3.0) steps are:

1. `kubectl apply -f ./deploy`

![image](https://user-images.githubusercontent.com/4496641/69952146-89efdb00-1531-11ea-8a31-4617fd922b73.png)

the config `ingressUrlFormat` is `ingressUrlFormat: "{{$jobCluster}}"`

2. `kubectl apply -f examples/wordcount/flink-operator-custom-resource.yaml`
the docker image is the latest..

**Comment by anandswaminathan** [comment]
@caryyu I am unable to find the image `docker.io/lyft/wordcount-operator-example:latest` here https://hub.docker.com/r/lyft/wordcount-operator-example/tags?page=1&name=latest

Can you try with the image - `docker.io/lyft/wordcount-operator-example:c9d77b83d39b97443e1d71e2531e7f3d76f15053`

I actually know what the issue is - this is not operator related. This happens if flink config contains invalid characters like `$`, which would happen depending on how the docker entrypoint is setup.

**Comment by caryyu** [comment]
@anandswaminathan that's great, it works
