### ISSUE TITLE
Question: how to auto-generate the crd.yaml after modify the types.go?

### ISSUE THREAD

**Issue by shuiqiangchen** [lyft/flinkk8soperator#140]
Hi, I learned that it is using the kubebuilder framework to build up this operator. But following the tutorial instruction of kubebuilder, it can not update the crd.yaml after modifying the types.go(add/delete fields). I wish it could be like the operator-sdk that would auto general the crd.yaml after applying "operator-sdk generate k8s/openapi". Am I missing any essential configuration? thank you!

**Comment by anandswaminathan** [comment]
Can you try `make generate` ?

Also I believe you need to have done `dep ensure` before that. More info here: https://github.com/lyft/flinkk8soperator/blob/master/docs/local_dev.md

Will add info to auto-generate also in there

**Comment by shuiqiangchen** [comment]
Yeah, I have doen dep ensure, and run 'make generate' after edited the types.go. This is my pr: https://github.com/lyft/flinkk8soperator/pull/141, please point it out if there was any mistake. Thank you!

**Comment by anandswaminathan** [comment]
I see the generated part. 

Sorry crd.yaml is currently manual. You would need to add validation manually for now.

**Comment by mwylde** [comment]
Hey @shuiqiangchen — the crd.yaml is not automatically managed. You will need to add your fields to it manually.

**Comment by shuiqiangchen** [comment]
Got it! Thank you for the clarification.
