### ISSUE TITLE
Using environment variables in programArgs

### ISSUE THREAD

**Issue by jverre** [lyft/flinkk8soperator#176]
Hi,

Currently the supported way of passing arguments to a job is by supplying programArgs in the custom resource but it doesn't seem possible to use environment variables to pass secrets.

Am I missing something ?

**Comment by anandswaminathan** [comment]
@jverre We support passing Env to Task and Job manager.  Check this https://github.com/lyft/flinkk8soperator/blob/master/pkg/apis/app/v1beta1/types.go#L116

**Comment by jverre** [comment]
Awesome, thanks a lot !
