### ISSUE TITLE
Better support for Flink 1.10

### ISSUE THREAD

**Issue by yuchaoran2011** [lyft/flinkk8soperator#185]
The operator at its current state is already working for Flink 1.10 jobs. But better support can be added especially for new memory configurations introduced in 1.10. For example, the operator currently gets task manager off-heap memory fraction and total memory requirement from the CustomResource spec and then computes the off-heap memory size. This is no longer needed for Flink 1.10 (although we do want to keep it for 1.9 backward compatibility) because simply setting `taskmanager.memory.flink.size` will do.

**Comment by HunterEl** [comment]
Would love to see support for this!

**Comment by yuchaoran2011** [comment]
#207 should address this issue.
