### ISSUE TITLE
docker.io/lyft/flinkk8soperator:v0.5.0 is missing in docker registry

### ISSUE THREAD

**Issue by jaroslaw-osmanski** [lyft/flinkk8soperator#198]
I cannot install flink operator new 0.5.0 version. I believe it's becuase  docker.io/lyft/flinkk8soperator:v0.5.0 is missing in docker registry. Travis job (https://travis-ci.org/github/lyft/flinkk8soperator/jobs/681214370) failed to push the image.

**Comment by anandswaminathan** [comment]
Fixed here: https://hub.docker.com/layers/lyft/flinkk8soperator/v0.5.0/images/sha256-ea13314836efbde800399cc40469022d4bb6ed4a305690db888cadbb8ccf1fa9?context=repo
