### ISSUE TITLE
Question: why do we have to build job JAR into the image?

### ISSUE THREAD

**Issue by functicons** [lyft/flinkk8soperator#20]
Just wondering about the design, why do we have to build job JAR into the image? Wouldn't it be more user-friendly, if we use the same Flink image with job JAR downloaded dynamically? Local JAR could be an option as well.

Is there any technical difficulty preventing us from doing this?

**Comment by yuchaoran2011** [comment]
This [blogpost](https://jobs.zalando.com/tech/blog/running-apache-flink-on-kubernetes/) provides some explanations on why baking the application jar in the job image can be a good thing. It really comes down to whether you want to run your Flink job in Job Cluster mode or Session Cluster mode. The blogpost argues for the former:

> Out of the two modes described in the previous section, we chose to run Flink as a Job Cluster. Two reasons drove the decision: The first reason is that the Docker image for Job Clusters needs to include the JAR with the Flink Job. This neatly solves the compliance problem as we can re-use the same workflow as we are using for regular JVM applications. The second advantage is that this deployment model allows to scale Task Managers independently for each Flink Job.

**Comment by anandswaminathan** [comment]
Hey @functicons,

You are right. The JAR need not be part of the image. It is just one of the way to do it. You can have JAR downloaded dynamically as well. Please try it out. The operator tries submit Job to the job manager if there is no job already running in the cluster. So as long as you have an image in which the Job manager can accept [Jars run](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jars-jarid-run), things should work fine.

**Comment by functicons** [comment]
Thanks @yuchaoran2011 and @anandswaminathan!
