### ISSUE TITLE
Is there a way to customize the readinessProbe for the JM

### ISSUE THREAD

**Issue by rjbordon** [lyft/flinkk8soperator#226]
I've noticed that the JM k8s deploy/pod is being created with a readiness probe with a default timeout of 1 second against the **/overview** route.

Also, I've realized on certain occasions that timeout is not enough but the **/overview** route resolves after a few more seconds, so I would like to set up a different timeout. 

I was not able to find out a reference to such a config on https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md.

**Comment by mareksimunek** [comment]
Hi, @rjbordon May I ask, how did you solve it? We are facing same issues with too short timeout for readinessProbe which restarts JM.
