### ISSUE TITLE
Integrating operator with AWS role/KIAM

### ISSUE THREAD

**Issue by mariogeorgievft** [lyft/flinkk8soperator#29]
Hello guys,

I watched your talk @ Flink Forward and I thought it was a great addition for the community, but at the time then it was not publicly available, since it is now, i have a question

When you create the Flink job cluster for instance in EKS @ AWS, how do you put a role for the pods so they only access what the role permits them and not the whole AWS. 

We are doing that with KIAM for our ordinary deployments, but the operator does not seem to have such addition, can you elaborate on the case?

Much Thanks,

Mario

**Comment by anandswaminathan** [comment]
@mariogeorgievft 

Any annotations that you add to the flink application resource pass is passed as an annotation to underlying deployment created by the operator.
 
Check [this](https://github.com/uswitch/kiam/blob/master/README.md)

I believe you are adding annotation `iam.amazonaws.com/role` to your ordinary deployment right? You can do the same while creating the flink application resource as well.
