### ISSUE TITLE
How to add a jar from local path

### ISSUE THREAD

**Issue by despondency** [lyft/flinkk8soperator#34]
Hello, 

If for instance you want to add jar from local path, how would you do it? It appears that it is not possible at the moment. You have to have the code for the jar located because the Dockerfile actually mvn packages the whole thing?
For instance if i want to run the flink-examples, i'd have to clone the code, rather than download the jar or even refer it from mvnrepository.

Thanks!

**Comment by despondency** [comment]
Hello, 

Referring it in the Dockerfile does the trick, however i've come across multiple times that the job got stuck in failing to savepoint resulting in it being stuck indefinetely and not being able to forcefully delete it. 

It would be good to think about a way to be able to just refer latest version of flink as image and give the jar from nexus/mvn repo and have it uploaded to the cluster without the need of having it pre packaged in the image itself.

**Comment by anandswaminathan** [comment]
@despondency 

You can set the `deleteMode: None` to the flink application custom resource if you do not want to block the deletion on Savepointing.

Also Flink operator do not have any restriction on how to package jars within the image. Users are always free to have their own way of getting the jars into the image. In our current implementation, the operator only expects the Image able accept [Job submission](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jars-jarid-run)  requests through API. The [example](https://github.com/lyft/flinkk8soperator/tree/master/examples/wordcount) is just one way of doing things. Feel free to try out other ways, and also contribute back alternate example approaches.
