### ISSUE TITLE
Cannot delete application under certain conditions

### ISSUE THREAD

**Issue by jmdacruz** [lyft/flinkk8soperator#58]
Trying to run `kubectl delete` on a previously created application (using the word count example) will hang forever under certain conditions. I run into this situation completely by mistake: I added zookeeper support to my FlinkApplication resource and made the mistake of pointing `high-availability.storageDir` to a local directory that did not exist on the container, causing the Job Manager to fail when trying to create the directory (probably because of a lack of permissions). Once in this state, the operator cannot upload tasks to the Job Manager.

I naturally decided to run `kubectl delete` on the application and fix my mistake, but at this point `kubectl` will simply wait forever and do nothing. Looking at the deployments, everything seems to be intact (i.e., nothing is being deleted). I even tried to manually delete everything, to no avail: Kubernetes says that the application is in the process of being deleted and refuses to let go, even after trying to force deletion. I'd be more than happy to provide logs upon request.

Update: I can create and delete new applications (without the mistake I mention above) that work just fine, but I just can't delete the faulty one

**Comment by anandswaminathan** [comment]
Hi @jmdacruz,

We currently support several modes for deletion - `Savepoint`, `ForceCancel`, `None`. The default option is `Savepoint`.
Details here: https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md

I assume in your case, the application is stuck on deleting, as it is unable to create a final savepoint. Set the value of `deleteMode` to `None` - If you do not want the application to create a final savepoint. 

Also to remove your application that is stuck, you can manually fix it by deleting the finalizer in the application metadata 
```  finalizers:
  - job.finalizers.flink.k8s.io
```
