### ISSUE TITLE
Question: where did the example submit the job?

### ISSUE THREAD

**Issue by TisonKun** [lyft/flinkk8soperator#59]
I find following description in example/README.md

> The operator submits the flink job through the REST API in the Jobmanager. For this to work, the jar file of the application needs to be present in the folder as indicated by the config value web.upload.dir.

it says that flink k8s operator first deploy the job manager and then **submit the job via REST API**, but I cannot find related code or command.

**Comment by anandswaminathan** [comment]
The operator submits the Job to the Jobmanager during the `SubmittingJob` phase.

The code for handling `SubmittingJob` phase is [here](https://github.com/lyft/flinkk8soperator/blob/master/pkg/controller/flinkapplication/flink_state_machine.go#L411) which invokes [this](https://github.com/lyft/flinkk8soperator/blob/master/pkg/controller/flink/client/api.go#L213)

**Comment by TisonKun** [comment]
Thanks for your explanation.

Closing...
