### ISSUE TITLE
Have a way to disable creation of ingress url in config.yaml 

### ISSUE THREAD

**Issue by soumyasmruti** [lyft/flinkk8soperator#66]

**Comment by anandswaminathan** [comment]
@soumyasmruti 

Currently the ingress creation is default. There is no way to disable it. If you are not going to be using the ingressUrl, you can just delete the `ingressUrlFormat` from the config map, and try out.
This will result in Ingress creation but with the `host` value empty. The operator should be able to proceed, and continue with other operations. Let me know if that works.

**Comment by soumyasmruti** [comment]
@anandswaminathan 

Thanks the suggestion worked.
