### ISSUE TITLE
Question: How can I work with savepointing periodically?

### ISSUE THREAD

**Issue by ssungmin** [lyft/flinkk8soperator#78]
Thank you for developing and open-sourcing this operator!
I'm a data engineer 
we're reviewing the potential usage of your Flink operator in our projects. 
we have a few question!!
 1. we want to run  savepointing periodically (ex . every 1 hour) 
 2. for data recovery or data reload ... 
   we want to run a new cluster that run as a savepoint at a specific point  in time

Is this possible ? 

Or what is the best way to do this?

**Comment by anandswaminathan** [comment]
@ssungmin 

With respect to (1), periodic savepointing feature is not available in the operator. I believe it should be easy to get that going, you can create a cron, that will issue - [savepoint post request](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jobs-jobid-savepoints)

(2) You can do this with the operator. When you create a flink application custom resource, you can specify the `savepointInfo` in the custom resource to make the application start from the savepoint. [details](https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md)

**Comment by ssungmin** [comment]
@anandswaminathan 
Thanks the suggestion !!
