### ISSUE TITLE
Running an Apache Beam pipeline

### ISSUE THREAD

**Issue by jmdacruz** [lyft/flinkk8soperator#79]
What would be the correct way of launching an Apache Beam pipeline using the operator? [This](https://beam.apache.org/documentation/runners/flink/#executing-a-beam-pipeline-on-a-flink-cluster) is the documentation provided by Apache Beam, but I'm not sure how to map it to an application on the operator.

**Comment by anandswaminathan** [comment]
cc @tweise

**Comment by tweise** [comment]
It is being discussed here: https://lists.apache.org/thread.html/a12dd939c4af254694481796bc08b05bb1321cfaadd1a79cd3866584@%3Cdev.beam.apache.org%3E

**Comment by jmdacruz** [comment]
Thanks for sharing @tweise. I'm thrilled to see the discussion on support for Python Apache Beam pipelines, that will be huge! At the moment, I'm only looking at Java Apache Beam pipelines, do you think these can be executed by the Flink operator as-is?

**Comment by tweise** [comment]
Yes, there is nothing extra needed when using the classic Flink runner. You should be able to build the fat far like you would for any other Flink job.

**Comment by jmdacruz** [comment]
@anandswaminathan I think it would be worth providing an example on how to launch a Java Apache Beam pipeline using the operator. For instance, the Apache Beam documentation uses Flink to run the Apache Beam pipeline and it passes a bunch of parameters that end in a FlinkPipelineOptions object. I understand that both these parameters and the contents of `flink-conf.yaml` are used to create an Apache Beam pipeline (see [here](https://github.com/apache/beam/blob/ae83448597f64474c3f5754d7b8e3f6b02347a6b/runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java#L144)), but it's not clear to me how these two set of parameters would be managed via the operator. Maybe @tweise can also shed some light here?

**Comment by tweise** [comment]
The operator has does not (need to) deal with FlinkPipelineOptions, that's a Beam concept local to the program entry point. Flink configuration should be managed like for any other Flink job through overrides in the CRD or though the conf that you have included into your container image.

For the pipeline submission, the Flink master URL should be [auto], since the Flink job needs to be submitted to the context execution environment.
https://github.com/apache/beam/blob/ae83448597f64474c3f5754d7b8e3f6b02347a6b/runners/flink/src/main/java/org/apache/beam/runners/flink/FlinkExecutionEnvironments.java#L158

**Comment by jmdacruz** [comment]
I think I'm probably missing something obvious here. If I understand correctly, the [Beam docs](https://beam.apache.org/documentation/runners/flink/#pipeline-options-for-the-flink-runner) it say that the pipeline options are passed as follows:

```shell
bin/flink run -c org.apache.beam.examples.WordCount /path/to/your.jar --runner=FlinkRunner --other-parameters
```

Where `--other-parameters` can include application-specific parameters. My question is: Is there a way for me to set these parameters on the `flinkConfig` section of the CRD, or do I need to pass them to my Docker image in a different way? My assumption is that I can use the same Dockerfile template (including the same [docker-entrypoint.sh](https://github.com/lyft/flinkk8soperator/blob/master/examples/wordcount/docker-entrypoint.sh)) for an Apache Beam pipeline, but maybe that's not the case and I need to tweak that?

**Comment by tweise** [comment]
The Beam "pipeline options" are nothing but arguments to the entry point. You would specify these as `programArgs` - see https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md

**Comment by jmdacruz** [comment]
Got it, thanks!
