### ISSUE TITLE
Question: Gitter/Slack chat room?

### ISSUE THREAD

**Issue by jmdacruz** [lyft/flinkk8soperator#80]
Is there a Gitter or Slack chatroom for asking questions and/or sharing information?

**Comment by anandswaminathan** [comment]
@jmdacruz Just created one. Will add to README.

https://flinkk8soperator.slack.com/

**Comment by jmdacruz** [comment]
Awesome! I think you'll need to provide an invite URL, since the current setup only allows `@lyft.com` email addresses to automatically register (@mwylde mentioned this on the PR too)
