### ISSUE TITLE
Wordcount example tags not accessible

### ISSUE THREAD

**Issue by yuchaoran2011** [lyft/flinkk8soperator#82]
The [quick start guide](https://github.com/lyft/flinkk8soperator/blob/master/docs/quick-start-guide.md) mentioned that all tags for the wordcount image can be found at https://cloud.docker.com/u/lyft/repository/registry-1.docker.io/lyft/wordcount-operator-example/tags. But it's not accessible to the public. I got a 404. Is this intended? On the other hand, I do have access to this list of [tags](https://hub.docker.com/r/lyft/wordcount-operator-example/tags). Did you mean to put this link in the doc?

**Comment by anandswaminathan** [comment]
@yuchaoran2011 yes.

Let me update it.
